version: "3"
services:
  jupyterlab:
    build: ./jupyterlab
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/app/data
